// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUFJK6H_FJSfNR8vkXQCbFRiDs4ZmVdeQ',
    appId: '1:662200938939:web:08e7c319df537113d4549e',
    messagingSenderId: '662200938939',
    projectId: 'chexagon-b0212',
    authDomain: 'chexagon-b0212.firebaseapp.com',
    storageBucket: 'chexagon-b0212.appspot.com',
    measurementId: 'G-HZ6YK70NHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO8p0DBkXYKAP89NSoh_I4l_aiV8uVL78',
    appId: '1:662200938939:android:4194eaa47bbaea17d4549e',
    messagingSenderId: '662200938939',
    projectId: 'chexagon-b0212',
    storageBucket: 'chexagon-b0212.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRtohJG842Npt_S50D7VGH4228oxxWaFg',
    appId: '1:662200938939:ios:37f420ea1796542ed4549e',
    messagingSenderId: '662200938939',
    projectId: 'chexagon-b0212',
    storageBucket: 'chexagon-b0212.appspot.com',
    iosClientId: '662200938939-igiob37e1pl1s12ipg61rdna5uj0khbm.apps.googleusercontent.com',
    iosBundleId: 'com.blasix.chexagon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRtohJG842Npt_S50D7VGH4228oxxWaFg',
    appId: '1:662200938939:ios:80e2c9968a425a0bd4549e',
    messagingSenderId: '662200938939',
    projectId: 'chexagon-b0212',
    storageBucket: 'chexagon-b0212.appspot.com',
    iosClientId: '662200938939-jnoal8h3kcmrtntd25qvg865h3761apc.apps.googleusercontent.com',
    iosBundleId: 'com.blasix.chexagon.RunnerTests',
  );
}
